name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install & Build
      run: |
        npm ci
        npm run docs:build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        user_name: "GitHub Actions"
        user_email: "actions@github.com"
        publish_branch: "gh-pages"
        publish_dir: ./docs/.vuepress/dist
        commit_message: 'deploy:'
